# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build

on:
  push:
    branches: [ "main", "alpha" ]
  pull_request:
    branches: [ "main", "alpha"  ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js rebuild --verbose

  publish-npm:
    # This needs to be done only when merge to main / master happens
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/alpha' }}

    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      # The "rush install" command installs package dependencies for all your
      # projects, based on the shrinkwrap file that is created/updated using "rush
      # update". 
      - name: Run 'rush install'
        run: node common/scripts/install-run-rush.js install --max-install-attempts 2

      - name: Run 'rush rebuild'
        run: node common/scripts/install-run-rush.js rebuild --verbose
      
      - name: Git config user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      
      - name: Run 'rush version --bump'
        if: ${{ github.ref == 'refs/heads/alpha' }}
        run: node common/scripts/install-run-rush.js version --bump

      - name: Run 'rush publish'
        # TODO: Remove suffix and this condition after testing.
        if: ${{ github.ref == 'refs/heads/alpha' }}
        run: node common/scripts/install-run-rush.js publish --apply --publish --include-all --set-access-level=public --suffix alpha
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
          
